# Hello and welcome to the config.yml file!
# I tried to simplify this as much as possible!

rules:
  enabled: true
  msg: "&6Rules: %line% &eRule 1: &fNo breaking the rules %line% &eRule 2: &fEdit this in the config! %line% &eRule 3: &fContact someone with console access if you see this" # %line% = next line

info:
  enabled: true
  msg: "&cIP: &6[Your IP] %line% &b*Insert Other Stuff Here* %line% &dIf you see this contact someone with console access!" # %line% = next line



console:
  enabled-msg: true # Will send a message in console if enabled.
  debug-mode: false # Sends messages in console! Only enable when there's an issue!