# Hello and welcome to the config.yml file!
# I tried to simplify this as much as possible!

rules:
  enabled: true
  msg: |
    Rule 1: No breaking the rules
    Rule 2: Edit this in the config!
    Rule 3: Contact someone with console access if you see this

info:
  enabled: true
  msg: |
    IP: [Your IP]
    *Insert Other Stuff Here*
    If you see this contact someone with console access!


console:
  enabled-msg: true # Will send a message in console if enabled.
  debug-mode: false # Sends messages in console! Only enable when there's an issue!